In [232]:
import pandas as pd
import numpy as np

In [233]:
df = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')

In [234]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

These are the features that I'm concerned about

In [235]:
df['Pclass'].unique(), df['SibSp'].unique(), df['Parch'].unique(),df['Cabin'].unique(),df['Embarked'].unique()

(array([3, 1, 2]),
 array([1, 0, 3, 4, 2, 5, 8]),
 array([0, 1, 2, 5, 3, 4, 6]),
 array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
        'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
        'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
        'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
        'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
        'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
        'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
        'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
        'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
        'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
        'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
        'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
        'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D4

In [236]:
df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [237]:
df['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

I hypothesized that we can make this better by applying the following changes
1. Convert cabin number to its cabin block. Fill nan with 'N' which basically means no room
2. Convert age into categories of group of ages
3. Covert fare into 4 categories according to its percentile
4. Convert name into prefix and Family name
5. Discard name and ticket


In [238]:
#cabin
def simplify_cabin():
    df['Cabin'] = df['Cabin'].fillna('N')
    df['Cabin'] = df['Cabin'].apply(lambda x: x[0])
    return df

In [239]:
#age
def simplify_age():
    bins = (-1,0,21,27,39,76)
    label = ['Unknown','0th_age','25th_age','50th_age','75th_age']
    df['Age'] = pd.cut(df['Age'],bins,labels=label)
    df['Age']=df['Age'].fillna('Unknown')
    return df

In [240]:
#fare
def simplify_fare():
    bins = (-1,0,8,14,32,513)
    label = ['Unknown','0th_fare','25th_fare','50th_fare','75th_fare']
    df['Fare'] = pd.cut(df['Fare'],bins,labels=label)
    df['Fare'] = df['Fare'].fillna('Unknown')
    return df

In [241]:
#Add prefix and family name
def simplify_name():
    df['Salutation'] = df['Name'].apply(lambda x: x.split(" ")[1])
    df['Surname'] = df['Name'].apply(lambda x: x.split(" ")[0])
    return df

In [242]:
#discard ticket number and name
def discard():
    return df.drop(['Name','Ticket'], axis = 1)

In [243]:
def transform_feature(df):
    df = simplify_cabin()
    df = simplify_age()
    df = simplify_fare()
    df = simplify_name()
    df = discard()
    return df

In [244]:
df = transform_feature(df)
df2 = transform_feature(df2)

TypeError: unorderable types: int() < str()